%    This is part of RMTool - Robot Motion Toolbox, for Matlab 2010b or newer.
%
%    Copyright (C) 2016 RMTool developing team. For people, details and citing 
%    information, please see: http://webdiis.unizar.es/RMTool/index.html.
%
%    This program is free software: you can redistribute it and/or modify
%    it under the terms of the GNU General Public License as published by
%    the Free Software Foundation, either version 3 of the License, or
%    (at your option) any later version.
%
%    This program is distributed in the hope that it will be useful,
%    but WITHOUT ANY WARRANTY; without even the implied warranty of
%    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%    GNU General Public License for more details.
%
%    You should have received a copy of the GNU General Public License
%    along with this program.  If not, see <http://www.gnu.org/licenses/>.

%% ============================================================================
%   MOBILE ROBOT TOOLBOX
%   Graphical User Interface
%   First version released on September, 2014. 
%   Last modification December 29, 2015.
%   More information: http://webdiis.unizar.es/RMTool
% ============================================================================


function [xref,yref,timeref] = re_sample(ref_trajectory, T)
%Reference trajectory (we re-sampled it, in order to have more points for the control algorithm
%instead of just single points (waypoints) generated by the path planner)
xref = ref_trajectory(1,:);
yref = ref_trajectory(2,:);
traj = [xref; yref];
traj_ini = [traj(1,1) traj(2,1)];
xref = traj(1,:);
yref = traj(2,:);
min_dist=T;%sampling period
new_traj=[traj(1,1);traj(2,1)];
new_traj=[];
timeref(1) = 0;
for i=1:(size(traj,2)-1)
    nr_points=ceil(norm(traj(:,i+1)-traj(:,i))/min_dist)+1; %number of intermetiate points
    nr_points=max(nr_points,2); %at least 2 points
    interm=linspace(0,1,nr_points); %equidistant values between 0 and 1
    %construct and add intermediate points
    new_traj=[new_traj, [(1-interm)*traj(1,i) + interm*traj(1,i+1) ; (1-interm)*traj(2,i) + interm*traj(2,i+1)] ];    
end
traj=new_traj;

%figure,plot(traj(1,:),traj(2,:),'xr');hold on;
%plot(xref,yref,'ob');

xref = traj(1,:);
yref = traj(2,:);
timeref = 0:T:(length(traj)*T);

end
